import type { AssetInput } from '@pascal-app/core'

/**
 * Catalog mebli — wygenerowany 2026-05-22 z `apps/editor/public/items/`
 * (145 prefab MIT, ich seed library). Podmieniony z oryginalnych Pascal
 * Supabase URL'i (byrpxoiotywskoojsrzd) na **self-hosted** asset paths
 * w naszym forku gsigrupa/editor → Vercel deploy gsi-plan-3d.vercel.app.
 *
 * Każda pozycja: relative paths (`/items/<slug>/...`) — Pascal viewer
 * resolver prepend'uje `NEXT_PUBLIC_ASSETS_CDN_URL` (set w env Vercel
 * project = https://gsi-plan-3d.vercel.app).
 *
 * Defaults dla dimensions/offset/rotation/scale = neutralne (1m × 1m × 1m).
 * Można dotunować per item gdy potrzeba precyzji.
 *
 * Heurystyka kategorii z nazwy slugu:
 *   - bathroom-*, *sink, bathtub, toilet, shower → bathroom (11)
 *   - kitchen*, *oven, *stove, *coffee, *fridge → kitchen (15)
 *   - ac-*, air-condition*, fan-*, *appliance → appliance (12)
 *   - tree, bush, cactus, plant, outdoor, pool → outdoor (12)
 *   - reszta (chair, couch, table, bed, etc.) → furniture (95)
 */

export const CATALOG_ITEMS: AssetInput[] = [
  {
    id: 'ac-block',
    category: 'appliance',
    name: 'Klimatyzator (blok)',
    tags: [],
    thumbnail: '/items/ac-block/thumbnail.webp',
    src: '/items/ac-block/model.glb',
    floorPlanUrl: '/items/ac-block/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'air-conditioner',
    category: 'appliance',
    name: 'Klimatyzator',
    tags: [],
    thumbnail: '/items/air-conditioner/thumbnail.webp',
    src: '/items/air-conditioner/model.glb',
    floorPlanUrl: '/items/air-conditioner/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'air-conditioner-block',
    category: 'appliance',
    name: 'Klimatyzator (blok)',
    tags: [],
    thumbnail: '/items/air-conditioner-block/thumbnail.webp',
    src: '/items/air-conditioner-block/model.glb',
    floorPlanUrl: '/items/air-conditioner-block/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'air-conditioning',
    category: 'appliance',
    name: 'Klimatyzacja',
    tags: [],
    thumbnail: '/items/air-conditioning/thumbnail.webp',
    src: '/items/air-conditioning/model.glb',
    floorPlanUrl: '/items/air-conditioning/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'alarm-keypad',
    category: 'appliance',
    name: 'Klawiatura alarmu',
    tags: [],
    thumbnail: '/items/alarm-keypad/thumbnail.webp',
    src: '/items/alarm-keypad/model.glb',
    floorPlanUrl: '/items/alarm-keypad/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ball',
    category: 'furniture',
    name: 'Piłka',
    tags: [],
    thumbnail: '/items/ball/thumbnail.webp',
    src: '/items/ball/model.glb',
    floorPlanUrl: '/items/ball/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'barbell',
    category: 'furniture',
    name: 'Sztanga',
    tags: [],
    thumbnail: '/items/barbell/thumbnail.webp',
    src: '/items/barbell/model.glb',
    floorPlanUrl: '/items/barbell/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'barbell-stand',
    category: 'furniture',
    name: 'Stojak na sztangę',
    tags: [],
    thumbnail: '/items/barbell-stand/thumbnail.webp',
    src: '/items/barbell-stand/model.glb',
    floorPlanUrl: '/items/barbell-stand/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'basket-hoop',
    category: 'furniture',
    name: 'Kosz do koszykówki',
    tags: [],
    thumbnail: '/items/basket-hoop/thumbnail.webp',
    src: '/items/basket-hoop/model.glb',
    floorPlanUrl: '/items/basket-hoop/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bathroom-sink',
    category: 'bathroom',
    name: 'Umywalka łazienkowa',
    tags: [],
    thumbnail: '/items/bathroom-sink/thumbnail.webp',
    src: '/items/bathroom-sink/model.glb',
    floorPlanUrl: '/items/bathroom-sink/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bathtub',
    category: 'bathroom',
    name: 'Wanna',
    tags: [],
    thumbnail: '/items/bathtub/thumbnail.webp',
    src: '/items/bathtub/model.glb',
    floorPlanUrl: '/items/bathtub/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bean-bag',
    category: 'furniture',
    name: 'Fotel pufa',
    tags: [],
    thumbnail: '/items/bean-bag/thumbnail.webp',
    src: '/items/bean-bag/model.glb',
    floorPlanUrl: '/items/bean-bag/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bedside-table',
    category: 'furniture',
    name: 'Szafka nocna',
    tags: [],
    thumbnail: '/items/bedside-table/thumbnail.webp',
    src: '/items/bedside-table/model.glb',
    floorPlanUrl: '/items/bedside-table/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'books',
    category: 'furniture',
    name: 'Książki',
    tags: [],
    thumbnail: '/items/books/thumbnail.webp',
    src: '/items/books/model.glb',
    floorPlanUrl: '/items/books/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bookshelf',
    category: 'furniture',
    name: 'Regał na książki',
    tags: [],
    thumbnail: '/items/bookshelf/thumbnail.webp',
    src: '/items/bookshelf/model.glb',
    floorPlanUrl: '/items/bookshelf/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bunkbed',
    category: 'furniture',
    name: 'Łóżko piętrowe',
    tags: [],
    thumbnail: '/items/bunkbed/thumbnail.webp',
    src: '/items/bunkbed/model.glb',
    floorPlanUrl: '/items/bunkbed/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'bush',
    category: 'outdoor',
    name: 'Krzak',
    tags: [],
    thumbnail: '/items/bush/thumbnail.webp',
    src: '/items/bush/model.glb',
    floorPlanUrl: '/items/bush/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'cactus',
    category: 'outdoor',
    name: 'Kaktus',
    tags: [],
    thumbnail: '/items/cactus/thumbnail.webp',
    src: '/items/cactus/model.glb',
    floorPlanUrl: '/items/cactus/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'car-toy',
    category: 'furniture',
    name: 'Samochodzik zabawka',
    tags: [],
    thumbnail: '/items/car-toy/thumbnail.webp',
    src: '/items/car-toy/model.glb',
    floorPlanUrl: '/items/car-toy/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ceiling-fan',
    category: 'furniture',
    name: 'Wentylator sufitowy',
    tags: [],
    thumbnail: '/items/ceiling-fan/thumbnail.webp',
    src: '/items/ceiling-fan/model.glb',
    floorPlanUrl: '/items/ceiling-fan/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ceiling-lamp',
    category: 'furniture',
    name: 'Lampa sufitowa',
    tags: [],
    thumbnail: '/items/ceiling-lamp/thumbnail.webp',
    src: '/items/ceiling-lamp/model.glb',
    floorPlanUrl: '/items/ceiling-lamp/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ceiling-light',
    category: 'furniture',
    name: 'Oświetlenie sufitowe',
    tags: [],
    thumbnail: '/items/ceiling-light/thumbnail.webp',
    src: '/items/ceiling-light/model.glb',
    floorPlanUrl: '/items/ceiling-light/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'circular-ceiling-light',
    category: 'furniture',
    name: 'Okrągła lampa sufitowa',
    tags: [],
    thumbnail: '/items/circular-ceiling-light/thumbnail.webp',
    src: '/items/circular-ceiling-light/model.glb',
    floorPlanUrl: '/items/circular-ceiling-light/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'closet',
    category: 'furniture',
    name: 'Szafa',
    tags: [],
    thumbnail: '/items/closet/thumbnail.webp',
    src: '/items/closet/model.glb',
    floorPlanUrl: '/items/closet/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'coat-rack',
    category: 'furniture',
    name: 'Wieszak na ubrania',
    tags: [],
    thumbnail: '/items/coat-rack/thumbnail.webp',
    src: '/items/coat-rack/model.glb',
    floorPlanUrl: '/items/coat-rack/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'coffee-machine',
    category: 'kitchen',
    name: 'Ekspres do kawy',
    tags: [],
    thumbnail: '/items/coffee-machine/thumbnail.webp',
    src: '/items/coffee-machine/model.glb',
    floorPlanUrl: '/items/coffee-machine/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'coffee-table',
    category: 'kitchen',
    name: 'Stolik kawowy',
    tags: [],
    thumbnail: '/items/coffee-table/thumbnail.webp',
    src: '/items/coffee-table/model.glb',
    floorPlanUrl: '/items/coffee-table/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'column',
    category: 'furniture',
    name: 'Słup',
    tags: [],
    thumbnail: '/items/column/thumbnail.webp',
    src: '/items/column/model.glb',
    floorPlanUrl: '/items/column/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'computer',
    category: 'appliance',
    name: 'Komputer',
    tags: [],
    thumbnail: '/items/computer/thumbnail.webp',
    src: '/items/computer/model.glb',
    floorPlanUrl: '/items/computer/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'couch-medium',
    category: 'furniture',
    name: 'Sofa średnia',
    tags: [],
    thumbnail: '/items/couch-medium/thumbnail.webp',
    src: '/items/couch-medium/model.glb',
    floorPlanUrl: '/items/couch-medium/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'couch-small',
    category: 'furniture',
    name: 'Sofa mała',
    tags: [],
    thumbnail: '/items/couch-small/thumbnail.webp',
    src: '/items/couch-small/model.glb',
    floorPlanUrl: '/items/couch-small/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'cutting-board',
    category: 'furniture',
    name: 'Deska do krojenia',
    tags: [],
    thumbnail: '/items/cutting-board/thumbnail.webp',
    src: '/items/cutting-board/model.glb',
    floorPlanUrl: '/items/cutting-board/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'desk',
    category: 'furniture',
    name: 'Biurko',
    tags: [],
    thumbnail: '/items/desk/thumbnail.webp',
    src: '/items/desk/model.glb',
    floorPlanUrl: '/items/desk/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'dining-chair',
    category: 'furniture',
    name: 'Krzesło jadalniane',
    tags: [],
    thumbnail: '/items/dining-chair/thumbnail.webp',
    src: '/items/dining-chair/model.glb',
    floorPlanUrl: '/items/dining-chair/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'dining-table',
    category: 'furniture',
    name: 'Stół jadalniany',
    tags: [],
    thumbnail: '/items/dining-table/thumbnail.webp',
    src: '/items/dining-table/model.glb',
    floorPlanUrl: '/items/dining-table/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'door',
    category: 'furniture',
    name: 'Drzwi',
    tags: [],
    thumbnail: '/items/door/thumbnail.webp',
    src: '/items/door/model.glb',
    floorPlanUrl: '/items/door/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'door-bar',
    category: 'furniture',
    name: 'Drzwi z drążkiem',
    tags: [],
    thumbnail: '/items/door-bar/thumbnail.webp',
    src: '/items/door-bar/model.glb',
    floorPlanUrl: '/items/door-bar/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'door-with-bar',
    category: 'furniture',
    name: 'Drzwi z drążkiem',
    tags: [],
    thumbnail: '/items/door-with-bar/thumbnail.webp',
    src: '/items/door-with-bar/model.glb',
    floorPlanUrl: '/items/door-with-bar/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'doorway-front',
    category: 'furniture',
    name: 'Otwór drzwiowy',
    tags: [],
    thumbnail: '/items/doorway-front/thumbnail.webp',
    src: '/items/doorway-front/model.glb',
    floorPlanUrl: '/items/doorway-front/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'double-bed',
    category: 'furniture',
    name: 'Łóżko podwójne',
    tags: [],
    thumbnail: '/items/double-bed/thumbnail.webp',
    src: '/items/double-bed/model.glb',
    floorPlanUrl: '/items/double-bed/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'dresser',
    category: 'furniture',
    name: 'Komoda',
    tags: [],
    thumbnail: '/items/dresser/thumbnail.webp',
    src: '/items/dresser/model.glb',
    floorPlanUrl: '/items/dresser/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'drying-rack',
    category: 'furniture',
    name: 'Suszarka',
    tags: [],
    thumbnail: '/items/drying-rack/thumbnail.webp',
    src: '/items/drying-rack/model.glb',
    floorPlanUrl: '/items/drying-rack/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'easel',
    category: 'furniture',
    name: 'Easel',
    tags: [],
    thumbnail: '/items/easel/thumbnail.webp',
    src: '/items/easel/model.glb',
    floorPlanUrl: '/items/easel/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'electric-panel',
    category: 'kitchen',
    name: 'Electric Panel',
    tags: [],
    thumbnail: '/items/electric-panel/thumbnail.webp',
    src: '/items/electric-panel/model.glb',
    floorPlanUrl: '/items/electric-panel/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ev-wall-charger',
    category: 'furniture',
    name: 'Ev Wall Charger',
    tags: [],
    thumbnail: '/items/ev-wall-charger/thumbnail.webp',
    src: '/items/ev-wall-charger/model.glb',
    floorPlanUrl: '/items/ev-wall-charger/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'exercise-bike',
    category: 'furniture',
    name: 'Exercise Bike',
    tags: [],
    thumbnail: '/items/exercise-bike/thumbnail.webp',
    src: '/items/exercise-bike/model.glb',
    floorPlanUrl: '/items/exercise-bike/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'exit-sign',
    category: 'furniture',
    name: 'Exit Sign',
    tags: [],
    thumbnail: '/items/exit-sign/thumbnail.webp',
    src: '/items/exit-sign/model.glb',
    floorPlanUrl: '/items/exit-sign/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fence',
    category: 'outdoor',
    name: 'Fence',
    tags: [],
    thumbnail: '/items/fence/thumbnail.webp',
    src: '/items/fence/model.glb',
    floorPlanUrl: '/items/fence/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fir-tree',
    category: 'outdoor',
    name: 'Fir Tree',
    tags: [],
    thumbnail: '/items/fir-tree/thumbnail.webp',
    src: '/items/fir-tree/model.glb',
    floorPlanUrl: '/items/fir-tree/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fire-alarm',
    category: 'appliance',
    name: 'Fire Alarm',
    tags: [],
    thumbnail: '/items/fire-alarm/thumbnail.webp',
    src: '/items/fire-alarm/model.glb',
    floorPlanUrl: '/items/fire-alarm/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fire-detector',
    category: 'furniture',
    name: 'Fire Detector',
    tags: [],
    thumbnail: '/items/fire-detector/thumbnail.webp',
    src: '/items/fire-detector/model.glb',
    floorPlanUrl: '/items/fire-detector/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fire-extinguisher',
    category: 'furniture',
    name: 'Fire Extinguisher',
    tags: [],
    thumbnail: '/items/fire-extinguisher/thumbnail.webp',
    src: '/items/fire-extinguisher/model.glb',
    floorPlanUrl: '/items/fire-extinguisher/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'flat-screen-tv',
    category: 'appliance',
    name: 'Flat Screen Tv',
    tags: [],
    thumbnail: '/items/flat-screen-tv/thumbnail.webp',
    src: '/items/flat-screen-tv/model.glb',
    floorPlanUrl: '/items/flat-screen-tv/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'floor-lamp',
    category: 'furniture',
    name: 'Floor Lamp',
    tags: [],
    thumbnail: '/items/floor-lamp/thumbnail.webp',
    src: '/items/floor-lamp/model.glb',
    floorPlanUrl: '/items/floor-lamp/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'freezer',
    category: 'furniture',
    name: 'Freezer',
    tags: [],
    thumbnail: '/items/freezer/thumbnail.webp',
    src: '/items/freezer/model.glb',
    floorPlanUrl: '/items/freezer/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fridge',
    category: 'kitchen',
    name: 'Fridge',
    tags: [],
    thumbnail: '/items/fridge/thumbnail.webp',
    src: '/items/fridge/model.glb',
    floorPlanUrl: '/items/fridge/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'fruits',
    category: 'furniture',
    name: 'Fruits',
    tags: [],
    thumbnail: '/items/fruits/thumbnail.webp',
    src: '/items/fruits/model.glb',
    floorPlanUrl: '/items/fruits/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'frying-pan',
    category: 'kitchen',
    name: 'Frying Pan',
    tags: [],
    thumbnail: '/items/frying-pan/thumbnail.webp',
    src: '/items/frying-pan/model.glb',
    floorPlanUrl: '/items/frying-pan/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'glass-door',
    category: 'furniture',
    name: 'Glass Door',
    tags: [],
    thumbnail: '/items/glass-door/thumbnail.webp',
    src: '/items/glass-door/model.glb',
    floorPlanUrl: '/items/glass-door/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'guitar',
    category: 'furniture',
    name: 'Guitar',
    tags: [],
    thumbnail: '/items/guitar/thumbnail.webp',
    src: '/items/guitar/model.glb',
    floorPlanUrl: '/items/guitar/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'hedge',
    category: 'furniture',
    name: 'Hedge',
    tags: [],
    thumbnail: '/items/hedge/thumbnail.webp',
    src: '/items/hedge/model.glb',
    floorPlanUrl: '/items/hedge/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'high-fence',
    category: 'outdoor',
    name: 'High Fence',
    tags: [],
    thumbnail: '/items/high-fence/thumbnail.webp',
    src: '/items/high-fence/model.glb',
    floorPlanUrl: '/items/high-fence/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'hood',
    category: 'furniture',
    name: 'Hood',
    tags: [],
    thumbnail: '/items/hood/thumbnail.webp',
    src: '/items/hood/model.glb',
    floorPlanUrl: '/items/hood/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'hydrant',
    category: 'furniture',
    name: 'Hydrant',
    tags: [],
    thumbnail: '/items/hydrant/thumbnail.webp',
    src: '/items/hydrant/model.glb',
    floorPlanUrl: '/items/hydrant/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'indoor-plant',
    category: 'outdoor',
    name: 'Indoor Plant',
    tags: [],
    thumbnail: '/items/indoor-plant/thumbnail.webp',
    src: '/items/indoor-plant/model.glb',
    floorPlanUrl: '/items/indoor-plant/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'iron',
    category: 'furniture',
    name: 'Iron',
    tags: [],
    thumbnail: '/items/iron/thumbnail.webp',
    src: '/items/iron/model.glb',
    floorPlanUrl: '/items/iron/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'ironing-board',
    category: 'furniture',
    name: 'Ironing Board',
    tags: [],
    thumbnail: '/items/ironing-board/thumbnail.webp',
    src: '/items/ironing-board/model.glb',
    floorPlanUrl: '/items/ironing-board/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kettle',
    category: 'furniture',
    name: 'Kettle',
    tags: [],
    thumbnail: '/items/kettle/thumbnail.webp',
    src: '/items/kettle/model.glb',
    floorPlanUrl: '/items/kettle/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kitchen',
    category: 'kitchen',
    name: 'Kitchen',
    tags: [],
    thumbnail: '/items/kitchen/thumbnail.webp',
    src: '/items/kitchen/model.glb',
    floorPlanUrl: '/items/kitchen/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kitchen-cabinet',
    category: 'kitchen',
    name: 'Kitchen Cabinet',
    tags: [],
    thumbnail: '/items/kitchen-cabinet/thumbnail.webp',
    src: '/items/kitchen-cabinet/model.glb',
    floorPlanUrl: '/items/kitchen-cabinet/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kitchen-counter',
    category: 'kitchen',
    name: 'Kitchen Counter',
    tags: [],
    thumbnail: '/items/kitchen-counter/thumbnail.webp',
    src: '/items/kitchen-counter/model.glb',
    floorPlanUrl: '/items/kitchen-counter/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kitchen-fridge',
    category: 'kitchen',
    name: 'Kitchen Fridge',
    tags: [],
    thumbnail: '/items/kitchen-fridge/thumbnail.webp',
    src: '/items/kitchen-fridge/model.glb',
    floorPlanUrl: '/items/kitchen-fridge/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kitchen-shelf',
    category: 'kitchen',
    name: 'Kitchen Shelf',
    tags: [],
    thumbnail: '/items/kitchen-shelf/thumbnail.webp',
    src: '/items/kitchen-shelf/model.glb',
    floorPlanUrl: '/items/kitchen-shelf/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'kitchen-utensils',
    category: 'kitchen',
    name: 'Kitchen Utensils',
    tags: [],
    thumbnail: '/items/kitchen-utensils/thumbnail.webp',
    src: '/items/kitchen-utensils/model.glb',
    floorPlanUrl: '/items/kitchen-utensils/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'laundry-bag',
    category: 'furniture',
    name: 'Laundry Bag',
    tags: [],
    thumbnail: '/items/laundry-bag/thumbnail.webp',
    src: '/items/laundry-bag/model.glb',
    floorPlanUrl: '/items/laundry-bag/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'livingroom-chair',
    category: 'furniture',
    name: 'Livingroom Chair',
    tags: [],
    thumbnail: '/items/livingroom-chair/thumbnail.webp',
    src: '/items/livingroom-chair/model.glb',
    floorPlanUrl: '/items/livingroom-chair/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'lounge-chair',
    category: 'furniture',
    name: 'Lounge Chair',
    tags: [],
    thumbnail: '/items/lounge-chair/thumbnail.webp',
    src: '/items/lounge-chair/model.glb',
    floorPlanUrl: '/items/lounge-chair/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'low-fence',
    category: 'outdoor',
    name: 'Low Fence',
    tags: [],
    thumbnail: '/items/low-fence/thumbnail.webp',
    src: '/items/low-fence/model.glb',
    floorPlanUrl: '/items/low-fence/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'medium-fence',
    category: 'outdoor',
    name: 'Medium Fence',
    tags: [],
    thumbnail: '/items/medium-fence/thumbnail.webp',
    src: '/items/medium-fence/model.glb',
    floorPlanUrl: '/items/medium-fence/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'microwave',
    category: 'kitchen',
    name: 'Microwave',
    tags: [],
    thumbnail: '/items/microwave/thumbnail.webp',
    src: '/items/microwave/model.glb',
    floorPlanUrl: '/items/microwave/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'office-chair',
    category: 'furniture',
    name: 'Office Chair',
    tags: [],
    thumbnail: '/items/office-chair/thumbnail.webp',
    src: '/items/office-chair/model.glb',
    floorPlanUrl: '/items/office-chair/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'office-table',
    category: 'furniture',
    name: 'Office Table',
    tags: [],
    thumbnail: '/items/office-table/thumbnail.webp',
    src: '/items/office-table/model.glb',
    floorPlanUrl: '/items/office-table/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'outdoor-playhouse',
    category: 'outdoor',
    name: 'Outdoor Playhouse',
    tags: [],
    thumbnail: '/items/outdoor-playhouse/thumbnail.webp',
    src: '/items/outdoor-playhouse/model.glb',
    floorPlanUrl: '/items/outdoor-playhouse/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'palm',
    category: 'furniture',
    name: 'Palm',
    tags: [],
    thumbnail: '/items/palm/thumbnail.webp',
    src: '/items/palm/model.glb',
    floorPlanUrl: '/items/palm/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'parking-spot',
    category: 'kitchen',
    name: 'Parking Spot',
    tags: [],
    thumbnail: '/items/parking-spot/thumbnail.webp',
    src: '/items/parking-spot/model.glb',
    floorPlanUrl: '/items/parking-spot/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'patio-umbrella',
    category: 'furniture',
    name: 'Patio Umbrella',
    tags: [],
    thumbnail: '/items/patio-umbrella/thumbnail.webp',
    src: '/items/patio-umbrella/model.glb',
    floorPlanUrl: '/items/patio-umbrella/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'piano',
    category: 'furniture',
    name: 'Piano',
    tags: [],
    thumbnail: '/items/piano/thumbnail.webp',
    src: '/items/piano/model.glb',
    floorPlanUrl: '/items/piano/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'picture',
    category: 'furniture',
    name: 'Picture',
    tags: [],
    thumbnail: '/items/picture/thumbnail.webp',
    src: '/items/picture/model.glb',
    floorPlanUrl: '/items/picture/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'pillar',
    category: 'furniture',
    name: 'Pillar',
    tags: [],
    thumbnail: '/items/pillar/thumbnail.webp',
    src: '/items/pillar/model.glb',
    floorPlanUrl: '/items/pillar/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'pool-table',
    category: 'outdoor',
    name: 'Pool Table',
    tags: [],
    thumbnail: '/items/pool-table/thumbnail.webp',
    src: '/items/pool-table/model.glb',
    floorPlanUrl: '/items/pool-table/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'recessed-light',
    category: 'furniture',
    name: 'Recessed Light',
    tags: [],
    thumbnail: '/items/recessed-light/thumbnail.webp',
    src: '/items/recessed-light/model.glb',
    floorPlanUrl: '/items/recessed-light/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'rectangular-carpet',
    category: 'furniture',
    name: 'Rectangular Carpet',
    tags: [],
    thumbnail: '/items/rectangular-carpet/thumbnail.webp',
    src: '/items/rectangular-carpet/model.glb',
    floorPlanUrl: '/items/rectangular-carpet/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'rectangular-ceiling-light',
    category: 'furniture',
    name: 'Rectangular Ceiling Light',
    tags: [],
    thumbnail: '/items/rectangular-ceiling-light/thumbnail.webp',
    src: '/items/rectangular-ceiling-light/model.glb',
    floorPlanUrl: '/items/rectangular-ceiling-light/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'rectangular-mirror',
    category: 'furniture',
    name: 'Rectangular Mirror',
    tags: [],
    thumbnail: '/items/rectangular-mirror/thumbnail.webp',
    src: '/items/rectangular-mirror/model.glb',
    floorPlanUrl: '/items/rectangular-mirror/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'round-carpet',
    category: 'furniture',
    name: 'Round Carpet',
    tags: [],
    thumbnail: '/items/round-carpet/thumbnail.webp',
    src: '/items/round-carpet/model.glb',
    floorPlanUrl: '/items/round-carpet/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'round-mirror',
    category: 'furniture',
    name: 'Round Mirror',
    tags: [],
    thumbnail: '/items/round-mirror/thumbnail.webp',
    src: '/items/round-mirror/model.glb',
    floorPlanUrl: '/items/round-mirror/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'scooter',
    category: 'furniture',
    name: 'Scooter',
    tags: [],
    thumbnail: '/items/scooter/thumbnail.webp',
    src: '/items/scooter/model.glb',
    floorPlanUrl: '/items/scooter/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sewing-machine',
    category: 'furniture',
    name: 'Sewing Machine',
    tags: [],
    thumbnail: '/items/sewing-machine/thumbnail.webp',
    src: '/items/sewing-machine/model.glb',
    floorPlanUrl: '/items/sewing-machine/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'shelf',
    category: 'furniture',
    name: 'Shelf',
    tags: [],
    thumbnail: '/items/shelf/thumbnail.webp',
    src: '/items/shelf/model.glb',
    floorPlanUrl: '/items/shelf/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'shower',
    category: 'bathroom',
    name: 'Shower',
    tags: [],
    thumbnail: '/items/shower/thumbnail.webp',
    src: '/items/shower/model.glb',
    floorPlanUrl: '/items/shower/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'shower-angle',
    category: 'bathroom',
    name: 'Shower Angle',
    tags: [],
    thumbnail: '/items/shower-angle/thumbnail.webp',
    src: '/items/shower-angle/model.glb',
    floorPlanUrl: '/items/shower-angle/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'shower-rug',
    category: 'bathroom',
    name: 'Shower Rug',
    tags: [],
    thumbnail: '/items/shower-rug/thumbnail.webp',
    src: '/items/shower-rug/model.glb',
    floorPlanUrl: '/items/shower-rug/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'shower-square',
    category: 'bathroom',
    name: 'Shower Square',
    tags: [],
    thumbnail: '/items/shower-square/thumbnail.webp',
    src: '/items/shower-square/model.glb',
    floorPlanUrl: '/items/shower-square/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'single-bed',
    category: 'furniture',
    name: 'Single Bed',
    tags: [],
    thumbnail: '/items/single-bed/thumbnail.webp',
    src: '/items/single-bed/model.glb',
    floorPlanUrl: '/items/single-bed/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sink-cabinet',
    category: 'bathroom',
    name: 'Sink Cabinet',
    tags: [],
    thumbnail: '/items/sink-cabinet/thumbnail.webp',
    src: '/items/sink-cabinet/model.glb',
    floorPlanUrl: '/items/sink-cabinet/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'skate',
    category: 'furniture',
    name: 'Deskorolka',
    tags: [],
    thumbnail: '/items/skate/thumbnail.webp',
    src: '/items/skate/model.glb',
    floorPlanUrl: '/items/skate/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'small-indoor-plant',
    category: 'outdoor',
    name: 'Mała roślina doniczkowa',
    tags: [],
    thumbnail: '/items/small-indoor-plant/thumbnail.webp',
    src: '/items/small-indoor-plant/model.glb',
    floorPlanUrl: '/items/small-indoor-plant/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'small-kitchen-cabinet',
    category: 'kitchen',
    name: 'Mała szafka kuchenna',
    tags: [],
    thumbnail: '/items/small-kitchen-cabinet/thumbnail.webp',
    src: '/items/small-kitchen-cabinet/model.glb',
    floorPlanUrl: '/items/small-kitchen-cabinet/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'smoke-detector',
    category: 'furniture',
    name: 'Czujnik dymu',
    tags: [],
    thumbnail: '/items/smoke-detector/thumbnail.webp',
    src: '/items/smoke-detector/model.glb',
    floorPlanUrl: '/items/smoke-detector/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sofa',
    category: 'furniture',
    name: 'Sofa',
    tags: [],
    thumbnail: '/items/sofa/thumbnail.webp',
    src: '/items/sofa/model.glb',
    floorPlanUrl: '/items/sofa/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sprinkler',
    category: 'furniture',
    name: 'Zraszacz',
    tags: [],
    thumbnail: '/items/sprinkler/thumbnail.webp',
    src: '/items/sprinkler/model.glb',
    floorPlanUrl: '/items/sprinkler/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'stairs',
    category: 'furniture',
    name: 'Schody',
    tags: [],
    thumbnail: '/items/stairs/thumbnail.webp',
    src: '/items/stairs/model.glb',
    floorPlanUrl: '/items/stairs/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'stereo-speaker',
    category: 'appliance',
    name: 'Głośnik stereo',
    tags: [],
    thumbnail: '/items/stereo-speaker/thumbnail.webp',
    src: '/items/stereo-speaker/model.glb',
    floorPlanUrl: '/items/stereo-speaker/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'stool',
    category: 'furniture',
    name: 'Stołek',
    tags: [],
    thumbnail: '/items/stool/thumbnail.webp',
    src: '/items/stool/model.glb',
    floorPlanUrl: '/items/stool/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'stove',
    category: 'kitchen',
    name: 'Kuchenka',
    tags: [],
    thumbnail: '/items/stove/thumbnail.webp',
    src: '/items/stove/model.glb',
    floorPlanUrl: '/items/stove/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'sunbed',
    category: 'furniture',
    name: 'Leżak',
    tags: [],
    thumbnail: '/items/sunbed/thumbnail.webp',
    src: '/items/sunbed/model.glb',
    floorPlanUrl: '/items/sunbed/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'suspended-fireplace',
    category: 'furniture',
    name: 'Kominek wiszący',
    tags: [],
    thumbnail: '/items/suspended-fireplace/thumbnail.webp',
    src: '/items/suspended-fireplace/model.glb',
    floorPlanUrl: '/items/suspended-fireplace/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'table',
    category: 'furniture',
    name: 'Stół',
    tags: [],
    thumbnail: '/items/table/thumbnail.webp',
    src: '/items/table/model.glb',
    floorPlanUrl: '/items/table/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'table-lamp',
    category: 'furniture',
    name: 'Lampa stołowa',
    tags: [],
    thumbnail: '/items/table-lamp/thumbnail.webp',
    src: '/items/table-lamp/model.glb',
    floorPlanUrl: '/items/table-lamp/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'television',
    category: 'furniture',
    name: 'Telewizor',
    tags: [],
    thumbnail: '/items/television/thumbnail.webp',
    src: '/items/television/model.glb',
    floorPlanUrl: '/items/television/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'tesla',
    category: 'furniture',
    name: 'Tesla',
    tags: [],
    thumbnail: '/items/tesla/thumbnail.webp',
    src: '/items/tesla/model.glb',
    floorPlanUrl: '/items/tesla/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'thermostat',
    category: 'appliance',
    name: 'Termostat',
    tags: [],
    thumbnail: '/items/thermostat/thumbnail.webp',
    src: '/items/thermostat/model.glb',
    floorPlanUrl: '/items/thermostat/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'threadmill',
    category: 'furniture',
    name: 'Bieżnia',
    tags: [],
    thumbnail: '/items/threadmill/thumbnail.webp',
    src: '/items/threadmill/model.glb',
    floorPlanUrl: '/items/threadmill/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'toaster',
    category: 'furniture',
    name: 'Toster',
    tags: [],
    thumbnail: '/items/toaster/thumbnail.webp',
    src: '/items/toaster/model.glb',
    floorPlanUrl: '/items/toaster/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'toilet',
    category: 'bathroom',
    name: 'Toaleta',
    tags: [],
    thumbnail: '/items/toilet/thumbnail.webp',
    src: '/items/toilet/model.glb',
    floorPlanUrl: '/items/toilet/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'toilet-brush',
    category: 'bathroom',
    name: 'Szczotka do WC',
    tags: [],
    thumbnail: '/items/toilet-brush/thumbnail.webp',
    src: '/items/toilet-brush/model.glb',
    floorPlanUrl: '/items/toilet-brush/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'toilet-paper',
    category: 'bathroom',
    name: 'Papier toaletowy',
    tags: [],
    thumbnail: '/items/toilet-paper/thumbnail.webp',
    src: '/items/toilet-paper/model.glb',
    floorPlanUrl: '/items/toilet-paper/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'toy',
    category: 'furniture',
    name: 'Zabawka',
    tags: [],
    thumbnail: '/items/toy/thumbnail.webp',
    src: '/items/toy/model.glb',
    floorPlanUrl: '/items/toy/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'trash-bin',
    category: 'furniture',
    name: 'Kosz na śmieci',
    tags: [],
    thumbnail: '/items/trash-bin/thumbnail.webp',
    src: '/items/trash-bin/model.glb',
    floorPlanUrl: '/items/trash-bin/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'tree',
    category: 'outdoor',
    name: 'Drzewo',
    tags: [],
    thumbnail: '/items/tree/thumbnail.webp',
    src: '/items/tree/model.glb',
    floorPlanUrl: '/items/tree/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'tub',
    category: 'furniture',
    name: 'Wanna',
    tags: [],
    thumbnail: '/items/tub/thumbnail.webp',
    src: '/items/tub/model.glb',
    floorPlanUrl: '/items/tub/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'tv-stand',
    category: 'appliance',
    name: 'Szafka pod telewizor',
    tags: [],
    thumbnail: '/items/tv-stand/thumbnail.webp',
    src: '/items/tv-stand/model.glb',
    floorPlanUrl: '/items/tv-stand/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'wall-art-06',
    category: 'furniture',
    name: 'Dekoracja ścienna 06',
    tags: [],
    thumbnail: '/items/wall-art-06/thumbnail.webp',
    src: '/items/wall-art-06/model.glb',
    floorPlanUrl: '/items/wall-art-06/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'wall-sink',
    category: 'bathroom',
    name: 'Umywalka ścienna',
    tags: [],
    thumbnail: '/items/wall-sink/thumbnail.webp',
    src: '/items/wall-sink/model.glb',
    floorPlanUrl: '/items/wall-sink/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'washing-machine',
    category: 'appliance',
    name: 'Pralka',
    tags: [],
    thumbnail: '/items/washing-machine/thumbnail.webp',
    src: '/items/washing-machine/model.glb',
    floorPlanUrl: '/items/washing-machine/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'window-double',
    category: 'furniture',
    name: 'Okno podwójne',
    tags: [],
    thumbnail: '/items/window-double/thumbnail.webp',
    src: '/items/window-double/model.glb',
    floorPlanUrl: '/items/window-double/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'window-large',
    category: 'furniture',
    name: 'Okno duże',
    tags: [],
    thumbnail: '/items/window-large/thumbnail.webp',
    src: '/items/window-large/model.glb',
    floorPlanUrl: '/items/window-large/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'window-rectangle',
    category: 'furniture',
    name: 'Okno prostokątne',
    tags: [],
    thumbnail: '/items/window-rectangle/thumbnail.webp',
    src: '/items/window-rectangle/model.glb',
    floorPlanUrl: '/items/window-rectangle/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'window-round',
    category: 'furniture',
    name: 'Okno okrągłe',
    tags: [],
    thumbnail: '/items/window-round/thumbnail.webp',
    src: '/items/window-round/model.glb',
    floorPlanUrl: '/items/window-round/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'window-simple',
    category: 'furniture',
    name: 'Okno proste',
    tags: [],
    thumbnail: '/items/window-simple/thumbnail.webp',
    src: '/items/window-simple/model.glb',
    floorPlanUrl: '/items/window-simple/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'window-small',
    category: 'furniture',
    name: 'Okno małe',
    tags: [],
    thumbnail: '/items/window-small/thumbnail.webp',
    src: '/items/window-small/model.glb',
    floorPlanUrl: '/items/window-small/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'window-small-2',
    category: 'furniture',
    name: 'Okno małe 2',
    tags: [],
    thumbnail: '/items/window-small-2/thumbnail.webp',
    src: '/items/window-small-2/model.glb',
    floorPlanUrl: '/items/window-small-2/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'window-square',
    category: 'furniture',
    name: 'Okno kwadratowe',
    tags: [],
    thumbnail: '/items/window-square/thumbnail.webp',
    src: '/items/window-square/model.glb',
    floorPlanUrl: '/items/window-square/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'window1-black-open-1731',
    category: 'furniture',
    name: 'Okno czarne otwierane',
    tags: [],
    thumbnail: '/items/window1-black-open-1731/thumbnail.webp',
    src: '/items/window1-black-open-1731/model.glb',
    floorPlanUrl: '/items/window1-black-open-1731/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'wine-bottle',
    category: 'furniture',
    name: 'Butelka wina',
    tags: [],
    thumbnail: '/items/wine-bottle/thumbnail.webp',
    src: '/items/wine-bottle/model.glb',
    floorPlanUrl: '/items/wine-bottle/thumbnail.webp',
    dimensions: [1, 1, 1],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
  },
]
